---
- name: update apt and install requirements
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: ensure Nodejs Repo is added
  shell: curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | sudo -E bash
  args:

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Install "create-task-cli" node.js package globally
  npm:
    name: "@_koii/create-task-cli"
    global: yes
